#Datasource configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#Log level configuration
logging.level.root=${LOGGING_LEVEL_ROOT:${LOGGING_LEVEL:error}}
logging.level.fr.perretpy=${LOGGING_LEVEL_PERRETPY:${LOGGING_LEVEL:error}}
logging.level.org.springframework.boot.autoconfigure.sql=${LOGGING_LEVEL_SQL:${LOGGING_LEVEL:error}}
logging.level.org.springframework.boot.web.embedded.tomcat=${LOGGING_LEVEL_TOMCAT:${LOGGING_LEVEL:error}}

spring.liquibase.enabled=true
spring.liquibase.contexts=prod
